[package]
name = "bevy_console"
version = "0.2.5"
edition = "2021"
authors = ["RichoDemus <git@richodemus.com>"]
homepage = "https://github.com/RichoDemus/bevy-console"
repository = "https://github.com/RichoDemus/bevy-console"
description = "dev console for bevy"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
examples = [
    "bevy/bevy_gltf",
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
]

[dependencies]
bevy_egui = "0"
bevy = { version = "0.6.1", default-features = false }

[dev-dependencies]
bevy = {version = "0.6", default-features = true}
